### ISSUE TITLE
extend seems to be broken

### ISSUE THREAD

**Issue by farzadso** [nuxt/renovate-config-nuxt#33]
Hi,

It seems like the `extends` option seems to be broken and isn't working anymore. I've received an automatic issue created by the `renovate`  bot mentioning this 👍 

```
There is an error with this repository's Renovate configuration that needs to be fixed. As a precaution, Renovate will stop PRs until it is resolved.

Error type: Cannot find preset's package (@nuxtjs)
```

You can find the issue created here : https://github.com/nuxt-community/universal-storage-module/issues/101

**Comment by rarkins** [comment]
Sorry, this was a cache glitch in the app which will auto-resolve itself.

**Comment by pi0** [comment]
Thanks @rarkins for fast reply. They started resolving :+1:
